### ISSUE TITLE
Saludos

### ISSUE THREAD

**Issue by JesusTics** [FcoCarreto/pizzaWeb#1]
Me gustaria saber, en que te puedo ayudar con la creacion de esta Pagina Web

**Comment by FcoCarreto** [comment]
Hola podrias ayudarme con la creacion de los clientes

**Comment by FcoCarreto** [comment]
mas o menos un archivo llamado cliente2 para que podamos ingresar los datos del cliente

**Comment by JesusTics** [comment]
Buenas tardes, claro que si, enseguida empiezo con el trabajo

**Comment by JesusTics** [comment]
Listo, ya le deje en verificación el documento que me indico.

**Comment by FcoCarreto** [comment]
Ok deja lo reviso
