### ISSUE TITLE
Funciones de los usuarios

### ISSUE THREAD

**Issue by JesusTics** [FcoCarreto/pizzaWeb#10]
En la parte de los usuarios me di cuenta que le faltarian unas funciones, estuve trabajando en la funcion de agregar y editar.
Ya casi las termino, no se si le gustaria que las agregue para que las verifique.

**Comment by FcoCarreto** [comment]
perfecto, espero a que los subas para su revisión. Si me parece buena idea implementar nuevas funciones, estaré al pendiente.

**Comment by JesusTics** [comment]
Listo, este tema ya quedo agregado a la rama main, por lo tanto cerrare este Issue
