### ISSUE TITLE
Creación de los Usuarios

### ISSUE THREAD

**Issue by FcoCarreto** [FcoCarreto/pizzaWeb#6]
Se necesitaría un archivo llamado indexU el cual tendrá un contenedor(puede usar el mismo código del contenedor del menú), las opciones que tendrá serán para agregar nuevos registros, para editarlos y borrarlos.
Otro archivo de eliminar que se llamara eliminarU, y su consulta será que eliminara de la tabla usuarios igualando su id con la id pulsada en el menú del usuario.

**Comment by FcoCarreto** [comment]
También podrías poner este código en el archivo de ingresar:
include("conexion.php");
Es que se me olvido.

**Comment by JesusTics** [comment]
Claro que si, ya agrego los archivos

**Comment by JesusTics** [comment]
Ya quedo los archivos que solicito amigo
